version: '3'

services:
  linkdnode0:
    container_name: linkdnode0
    image: "kfangw/linkdnode"
    environment:
      - ID=0
      - LOG=${LOG:-linkd.log}
    volumes:
      - ./build:/linkd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  linkdnode1:
    container_name: linkdnode1
    image: "kfangw/linkdnode"
    environment:
      - ID=1
      - LOG=${LOG:-linkd.log}
    volumes:
      - ./build:/linkd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  linkdnode2:
    container_name: linkdnode2
    image: "kfangw/linkdnode"
    environment:
      - ID=2
      - LOG=${LOG:-linkd.log}
    volumes:
      - ./build:/linkd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  linkdnode3:
    container_name: linkdnode3
    image: "kfangw/linkdnode"
    environment:
      - ID=3
      - LOG=${LOG:-linkd.log}
    volumes:
      - ./build:/linkd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

